version: '3.8'

services:
  database-todo:
    container_name: database-todo
    image: postgis/postgis:13-master
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'jesus'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'todo-list'
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '8123:80'
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'password'
