export enum DomainErrorCode {
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
  ACCOUNT_ALREADY_REGISTERED_ERROR = 'ACCOUNT_ALREADY_REGISTERED_ERROR',
  ACCOUNT_NOT_REGISTERED = 'ACCOUNT_NOT_REGISTERED',
  ACCOUNT_AUTHENTICATION_FAILED = 'ACCOUNT_AUTHENTICATION_FAILED',
  DUPLICATED_ID_CONFLICT = 'DUPLICATED_ID_CONFLICT',
}
